travel = ['hangzhou', 'beijing', 'xinjiang', 'haerbin', 'sanya']
print(travel)
print(sorted(travel))
print(travel)
print(sorted(travel))
print(travel)
travel.reverse()
print(travel)
travel.reverse()
print(travel)
travel.sort(reverse=True)
print(travel)
travel.sort()
print(travel)